### PR TITLE
Repurposed Shotgun - Heirloom item

### PR DESCRIPTION
**Pull request by SlamBamActionman**
## About the PR

Added Jalopy Oldman's Heirloom item, Repurposed Shotgun.
> Repurposed Shotgun
> A broken shotgun that no longer functions, repurposed into a capable smashing instrument. Percussive therapy.

## Why / Balance

The Repurposed Shotgun is a cosmetic variation on the Baseball Bat item. It features three minor changes:

- It's not craftable.
- It's not possible to use it as a rolling pin for dough.
- It's possible to wear it in the suitslot (similar to other guns) as opposed to only the backpack slot.

## Media

image
image
image
image
image
image
image
image

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Tych0theSynth** [comment]
First off, I think this looks great. This is a really nice sprite! :D

With this being a weapon and not a purely cosmetic item, I have a few questions about this from a GM point of view:
- Is this item intended for use when you play a specific job/role? If yes, which? 
- What item do you intend for this to replace for you and why?
- With regards to the above, does it do anything different to that item? Why?
- Is this something that replaces something standard-issue for any aforementioned roles? If not, in what circumstance or context would it be granted/used?

**Comment by Frostbitey** [comment]
> First off, I think this looks great. This is a really nice sprite! :D
> 
> With this being a weapon and not a purely cosmetic item, I have a few questions about this from a GM point of view:
> 
> * Is this item intended for use when you play a specific job/role? If yes, which?
> * What item do you intend for this to replace for you and why?
> * With regards to the above, does it do anything different to that item? Why?
> * Is this something that replaces something standard-issue for any aforementioned roles? If not, in what circumstance or context would it be granted/used?

About the statement "Not purely a cosmetic item", It is just a regular winter coat. With regular winter coat statistics, Just resprited.
1. This item is for Yarna-Crimson, for when they are a security member. Which is practically, always!
2. This item does not intend to replace Anything, It is just a new item. For Yarna, Purely. As just a cosmetic.
3. As said at the start, It is just a winter coat, with regular winter coat statistics.
4. As said before, this item is granted to Any security rank member. But again, Specifically to Yarna Crimson (OverwatchVoice).
I hope i understood all the questions correctly! If not, tell me!
Also thanks for the compliment :3

**Comment by Gotimanga** [comment]
@Frostbitey I'm sorry to say, but I think you're replying to the wrong PR

**Comment by Frostbitey** [comment]
> @Frostbitey I'm sorry to say, but I think you're replying to the wrong PR

My bad..

**Comment by Gotimanga** [comment]
No worries, I make mistakes like that oftentimes :)

**Comment by SlamBamActionman** [comment]
> First off, I think this looks great. This is a really nice sprite! :D
> 
> With this being a weapon and not a purely cosmetic item, I have a few questions about this from a GM point of view:
> 
> * Is this item intended for use when you play a specific job/role? If yes, which?
> * What item do you intend for this to replace for you and why?
> * With regards to the above, does it do anything different to that item? Why?
> * Is this something that replaces something standard-issue for any aforementioned roles? If not, in what circumstance or context would it be granted/used?

- The item is not intended for a specific role.
- Baseball bat; the bat is mostly used as a structural breaching/blunt weapon, making its stats suitable for anything that can be similarly used as a big sturdy hitting stick. Reusing an old reliable tool in an improvised new way is in line with Jalopy's character. Also hitting someone with the butt of a weapon is cool. 
- The item functions identically to a baseball bat, with the 3 exceptions listed in the PR description.
  - It shouldn't be craftable, as its an heirloom item
  - It shouldn't be able to roll dough (unless someone has irl experience with rolling dough using shotguns and can vouch for it being a viable option)
  - The only minor "buff" to the item is that it fits in the suitslot; while this does make it slightly more versitile, as the item is as large as a 2x2 oxygen tank it really just becomes a question of where in the inventory it is. Allowing it in the suitslot also makes it a better cosmetic option, instead of it having to take up the backpack slot. 
- It does not replace anything standard-issue and would be a one-time swap once a baseball bat is acquired, which afaik is allowed as stated here: https://discord.com/channels/1178043252969046027/1208920487267143711/1219622687257923635

**Comment by Aexxie** [comment]
> No worries, I make mistakes like that oftentimes :)

~~Just wait until you see how many times I've actually accidentally tried to PR a merge to upstream~~

**Review by Aexxie — CHANGES_REQUESTED** [review]
Remove underscores from RSI names **except** for the `_64x` one.

**Pull request merged**
